server:
  port: 8090

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/lms-auth?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_empty

springdoc:
  api-docs:
    path: /docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: GieJX^>%Pd;Z]#&?kmZY4SRZNlWsjr%JJiH!q9KM~,Zd./[oh*=dus&p_M3Ab#B
  accessExpiration: 7200
  refreshExpiration: 86400

management:
  endpoints:
    web:
      exposure:
        include: "*"
